services:
  langflow:
    container_name: langflow
    build:
        context: .
        dockerfile: docker/build_and_push.Dockerfile
    ports:
      - 7860:7860
    env_file: 
      - .env
    volumes:
      - langflow-data:/app/langflow

volumes:
  langflow-data:
